-- Postgres Fix: Add identity to asset_id and other PK columns
-- Run this on your Supabase/Postgres instance if you see "null value in column ... violates not-null constraint"
--
-- Notes:
-- - Targets schema novaquant_data (adjust if your NOVA_DATA_PG_SCHEMA differs).
-- - pg_get_serial_sequence() often returns NULL for bigint columns that only have DEFAULT nextval(...)
--   (not linked as SERIAL in catalog); we setval explicit *_id_seq where needed.

SET search_path TO novaquant_data, public;

-- 1. Fix assets table (Primary Key: asset_id)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'novaquant_data' AND table_name = 'assets'
  ) THEN
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'novaquant_data'
        AND table_name = 'assets'
        AND column_name = 'asset_id'
        AND (is_identity = 'YES' OR column_default IS NOT NULL)
    ) THEN
      ALTER TABLE novaquant_data.assets
        ALTER COLUMN asset_id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;

    BEGIN
      PERFORM setval(
        pg_get_serial_sequence('novaquant_data.assets', 'asset_id'),
        COALESCE((SELECT MAX(asset_id) FROM novaquant_data.assets), 0) + 1,
        false
      );
    EXCEPTION WHEN OTHERS THEN
      RAISE NOTICE 'Could not sync sequence for assets.asset_id: %', SQLERRM;
    END;
  END IF;
END $$;

-- 2. Sync sequences for tables with bigint `id` + nextval default (explicit sequence name)
DO $$
DECLARE
  t_name TEXT;
  tables_to_fix TEXT[] := ARRAY[
    'ingest_anomalies',
    'chat_audit_logs',
    'chat_messages',
    'signal_events',
    'signal_deliveries',
    'backtest_metrics',
    'backtest_artifacts',
    'audit_events'
  ];
  seq_fq TEXT;
BEGIN
  FOREACH t_name IN ARRAY tables_to_fix
  LOOP
    IF EXISTS (
      SELECT 1 FROM information_schema.tables
      WHERE table_schema = 'novaquant_data' AND table_name = t_name
    ) THEN
      seq_fq := format('%I.%I', 'novaquant_data', t_name || '_id_seq');

      IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'novaquant_data'
          AND table_name = t_name
          AND column_name = 'id'
          AND (is_identity = 'YES' OR column_default IS NOT NULL)
      ) THEN
        EXECUTE format(
          'ALTER TABLE novaquant_data.%I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY',
          t_name
        );
      END IF;

      BEGIN
        EXECUTE format(
          'SELECT setval(%L::regclass, COALESCE((SELECT MAX(id) FROM novaquant_data.%I), 0) + 1, false)',
          seq_fq,
          t_name
        );
      EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'Could not setval % for table %: %', seq_fq, t_name, SQLERRM;
      END;
    END IF;
  END LOOP;
END $$;
