// Generated by scripts/version-manager.mjs. Do not edit by hand.
export const APP_VERSION = '10.21.0';
export const APP_BUILD_NUMBER = 79;
export const APP_VERSION_LABEL = `v${APP_VERSION}`;

export const APP_METADATA = Object.freeze({
  semanticVersion: APP_VERSION,
  buildNumber: APP_BUILD_NUMBER,
  versionLabel: APP_VERSION_LABEL,
});

export function getAppVersionDisplay() {
  return `${APP_VERSION} (build ${APP_BUILD_NUMBER})`;
}
